language: java

before_script:
  - ci-tools/install_lbfgs.sh
  - ci-tools/install_crfsuite.sh
  - ci-tools/install_crfsuite-jni.sh

after_success:
  - mvn deploy --settings ../ci-tools/maven/settings.xml -Dmaven.test.skip=true
