CREATE TABLE LAUNCH (
id INT AUTO_INCREMENT PRIMARY KEY,
started TIMESTAMP NOT NULL
) ENGINE = MYISAM;

CREATE TABLE DOCUMENT (
id INT AUTO_INCREMENT PRIMARY KEY,
uri VARCHAR(256) NOT NULL,
size INT,
processing_time BIGINT,
launch_id INT NOT NULL,
CONSTRAINT document2launch FOREIGN KEY (launch_id) REFERENCES LAUNCH (id) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE = MYISAM;

CREATE TABLE SPAN (
id INT AUTO_INCREMENT PRIMARY KEY,
doc_id INT NOT NULL,
txt VARCHAR(512) NOT NULL,
CONSTRAINT span2document FOREIGN KEY (doc_id) REFERENCES DOCUMENT (id) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE = MYISAM;

CREATE TABLE ANNOTATION (
id INT AUTO_INCREMENT PRIMARY KEY,
anno_type VARCHAR(64) NOT NULL,
span_id INT NOT NULL,
txt VARCHAR(512),
start_offset INT NOT NULL,
end_offset INT NOT NULL,
CONSTRAINT annotation2span FOREIGN KEY (span_id) REFERENCES SPAN (id) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE = MYISAM;

CREATE TABLE FEATURE (
owner_anno_id INT NOT NULL,
value_anno_id INT,
feature_name VARCHAR(32) NOT NULL,
CONSTRAINT feature2annotation_owner FOREIGN KEY (owner_anno_id) REFERENCES ANNOTATION(id) ON DELETE CASCADE ON UPDATE RESTRICT,
CONSTRAINT feature2annotation_value FOREIGN KEY (value_anno_id) REFERENCES ANNOTATION(id) ON DELETE CASCADE ON UPDATE RESTRICT,
INDEX idx_owner_feature (owner_anno_id, feature_name)
) ENGINE = MYISAM;