/* The following code was generated by JFlex 1.4_5 on 14.02.13 2:23 */

// Sidikov Marsel

package tokenization;
import org.apache.uima.jcas.JCas;
import org.apache.uima.jcas.tcas.Annotation;
import tokenization.types.Letters;
import tokenization.types.Number;
import tokenization.types.Range;
import tokenization.types.TokenSeparator;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4_5
 * on 14.02.13 2:23 from the specification file
 * <tt>/home/marsel/workspace/NLP@Cloud/src/tokenization/JFlex_Tokenizer.flex</tt>
 */
public class JFlex_Tokenizer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int YY_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  private static final String yycmap_packed = 
    "\11\0\1\3\1\1\1\0\1\5\1\2\22\0\1\4\1\0\1\0"+
    "\1\0\1\0\1\0\2\0\2\0\1\0\1\10\1\7\1\11\1\7"+
    "\1\0\12\6\2\0\1\0\1\0\1\0\1\0\1\0\32\17\3\13"+
    "\1\13\1\13\1\13\32\20\4\13\44\13\1\13\1\13\1\13\u035b\13"+
    "\1\16\16\13\40\15\40\14\1\0\1\14\u1bc2\0\1\21\21\0\1\0"+
    "\174\0\1\0\10\0\1\0\u0165\0\1\12\udded\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] yycmap = yy_unpack_cmap(yycmap_packed);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] YY_ACTION = yy_unpack_YY_ACTION();

  private static final String YY_ACTION_packed0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\1\1\10\2\1\1\11\1\12\1\13\1\14\1\15"+
    "\2\0\1\10\1\16\1\13\1\16\1\12\1\14\1\17"+
    "\1\20\1\15\1\21\1\22\1\0\1\22\2\0\1\23"+
    "\1\22";

  private static int [] yy_unpack_YY_ACTION() {
    int [] result = new int[36];
    int offset = 0;
    offset = yy_unpack_YY_ACTION(YY_ACTION_packed0, offset, result);
    return result;
  }

  private static int yy_unpack_YY_ACTION(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] yy_rowMap = yy_unpack_yy_rowMap();

  private static final String yy_rowMap_packed0 =
    "\0\0\0\22\0\22\0\22\0\22\0\22\0\22\0\44"+
    "\0\66\0\110\0\132\0\154\0\176\0\220\0\242\0\264"+
    "\0\306\0\330\0\352\0\374\0\154\0\u010e\0\242\0\u0120"+
    "\0\u0132\0\u0144\0\u0156\0\u0168\0\u017a\0\u018c\0\u019e\0\22"+
    "\0\u01b0\0\u01c2\0\u01d4\0\u01c2";

  private static int [] yy_unpack_yy_rowMap() {
    int [] result = new int[36];
    int offset = 0;
    offset = yy_unpack_yy_rowMap(yy_rowMap_packed0, offset, result);
    return result;
  }

  private static int yy_unpack_yy_rowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = ((int) packed.charAt(i++)) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] yytrans = yy_unpack_yytrans();

  private static final String yytrans_packed0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\2"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\2\30\0\1\10\1\22\1\0\1\23\7\0"+
    "\1\23\6\0\1\10\24\0\1\23\7\0\1\23\6\0"+
    "\1\24\27\0\1\25\21\0\1\15\2\26\17\0\1\27"+
    "\1\30\1\26\17\0\1\27\2\26\17\0\1\25\2\0"+
    "\1\31\1\32\15\0\1\25\2\0\1\33\1\34\7\0"+
    "\1\35\21\0\1\36\1\0\1\37\1\40\1\37\15\0"+
    "\1\24\1\41\1\0\1\23\7\0\1\23\14\0\3\26"+
    "\17\0\1\26\1\30\1\26\22\0\1\31\1\33\20\0"+
    "\1\33\1\32\20\0\2\33\20\0\1\33\1\34\7\0"+
    "\1\35\2\0\1\23\7\0\1\23\6\0\1\36\1\42"+
    "\20\0\1\36\21\0\1\43\21\0\1\44\21\0\1\43"+
    "\2\0\1\23\7\0\1\23";

  private static int [] yy_unpack_yytrans() {
    int [] result = new int[486];
    int offset = 0;
    offset = yy_unpack_yytrans(yytrans_packed0, offset, result);
    return result;
  }

  private static int yy_unpack_yytrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int YY_UNKNOWN_ERROR = 0;
  private static final int YY_NO_MATCH = 1;
  private static final int YY_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] YY_ATTRIBUTE = yy_unpack_YY_ATTRIBUTE();

  private static final String YY_ATTRIBUTE_packed0 =
    "\1\0\6\11\12\1\2\0\13\1\1\0\1\11\2\0"+
    "\2\1";

  private static int [] yy_unpack_YY_ATTRIBUTE() {
    int [] result = new int[36];
    int offset = 0;
    offset = yy_unpack_YY_ATTRIBUTE(YY_ATTRIBUTE_packed0, offset, result);
    return result;
  }

  private static int yy_unpack_YY_ATTRIBUTE(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /* user code: */
	JCas UIMA_JCas;
	
	public JFlex_Tokenizer(java.io.Reader in, JCas UIMA_JCas) {
	this.UIMA_JCas = UIMA_JCas;
    this.yy_reader = in;
    }
    
	public boolean isEof() {
		return yy_atEOF;
	}
	
	Letters createLettersToken(String language, String letterCase) {
		Letters token = new Letters(UIMA_JCas);
		token.setLanguage(language);
		token.setLetterCase(letterCase);
		token.setBegin(yy_currentPos);
		token.setEnd(yy_currentPos+yylength());
		return token;
	}
	
	Number createNumberToken(String sign, String kind) {
		Number token = new Number(UIMA_JCas);
		token.setSign(sign);
		token.setKind(kind);
		token.setBegin(yy_currentPos);
		token.setEnd(yy_currentPos+yylength());
		return token;
	}
	
	Range createRangeToken() {
		Range token = new Range(UIMA_JCas);
		token.setBegin(yy_currentPos);
		token.setEnd(yy_currentPos+yylength());
		return token;
	}

	TokenSeparator createSeparatorToken(String typeValue) {
		TokenSeparator token = new TokenSeparator(UIMA_JCas);
		token.setBegin(yy_currentPos);
		token.setEnd(yy_currentPos+yylength());
		token.setTypeOfSeparator(typeValue);
		return token;
	}
		 


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public JFlex_Tokenizer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public JFlex_Tokenizer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] yy_unpack_cmap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 114) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) throws java.io.IOException {
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public Annotation yylex() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    int [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      yy_action = -1;

      yy_currentPos_l = yy_currentPos = yy_startRead = yy_markedPos_l;
  
      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {
    
          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action < 0 ? yy_action : YY_ACTION[yy_action]) {
        case 1: 
          { System.out.print(yytext()); }
        case 20: break;
        case 7: 
          { return createNumberToken("Positive", "Integer"); }
        case 21: break;
        case 6: 
          { return createSeparatorToken("Formfeed"); }
        case 22: break;
        case 5: 
          { return createSeparatorToken("Space"); }
        case 23: break;
        case 9: 
          { return createLettersToken("RU","Lower"); }
        case 24: break;
        case 13: 
          { return createLettersToken("EN","Lower"); }
        case 25: break;
        case 12: 
          { return createLettersToken("EN","Upper"); }
        case 26: break;
        case 19: 
          { return createNumberToken("Negative", "Real"); }
        case 27: break;
        case 3: 
          { return createSeparatorToken("Carriage return"); }
        case 28: break;
        case 14: 
          { return createLettersToken("RU","Capitalized"); }
        case 29: break;
        case 8: 
          { return createNumberToken("Negative", "Integer"); }
        case 30: break;
        case 11: 
          { return createLettersToken("RU","Mixed"); }
        case 31: break;
        case 17: 
          { return createNumberToken("Positive", "Real"); }
        case 32: break;
        case 16: 
          { return createLettersToken("EN","Mixed"); }
        case 33: break;
        case 4: 
          { return createSeparatorToken("Tabulation"); }
        case 34: break;
        case 15: 
          { return createLettersToken("EN","Capitalized"); }
        case 35: break;
        case 10: 
          { return createLettersToken("RU","Upper"); }
        case 36: break;
        case 18: 
          { return createRangeToken(); }
        case 37: break;
        case 2: 
          { return createSeparatorToken("New Line"); }
        case 38: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
              { return null;
 }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java JFlex_Tokenizer <inputfile>");
    }
    else {
      for (int i = 0; i < argv.length; i++) {
        JFlex_Tokenizer scanner = null;
        try {
          scanner = new JFlex_Tokenizer( new java.io.FileReader(argv[i]) );
          while ( !scanner.yy_atEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
